/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Walter Mercado' at '6/12/15 5:54 PM' with Gradle 2.2.1
 *
 * @author Walter Mercado, @date 6/12/15 5:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
